use super::super::super::selection::SelectionState;
use super::super::types::{
    CompositorCapabilities, DrawingState, MAX_STROKE_THICKNESS, MIN_STROKE_THICKNESS,
    PendingOnboardingUsage, PressureThicknessEditMode, PressureThicknessEntryMode, TextInputMode,
};
use super::structs::InputState;
use crate::config::{Action, BoardsConfig, PRESET_SLOTS_MAX, QuickColorPalette, Shortcut};
use crate::draw::{
    ArrowStyle, BlurStyle, DirtyTracker, EraserKind, FontDescriptor, REGULAR_POLYGON_DEFAULT_SIDES,
};
use crate::input::state::highlight::{ClickHighlightSettings, ClickHighlightState};
use crate::input::state::input_hud::{InputHudSettings, InputHudState};
use crate::input::{
    BoardManager,
    modifiers::{DragToolBindings, Modifiers},
    tool::{EraserMode, PerToolDrawingSettings},
};
use std::collections::{HashMap, HashSet};
use std::time::{SystemTime, UNIX_EPOCH};

/// Runtime values needed to construct an [`InputState`].
///
/// The backend translates configuration into this value. Input state does not
/// need to know which config sections supplied each setting, and call sites
/// cannot accidentally transpose same-typed positional arguments.
#[derive(Clone)]
pub(crate) struct InputStateSeed {
    pub(crate) color: crate::draw::Color,
    pub(crate) thickness: f64,
    pub(crate) eraser_size: f64,
    pub(crate) eraser_mode: EraserMode,
    pub(crate) marker_opacity: f64,
    pub(crate) fill_enabled: bool,
    pub(crate) font_size: f64,
    pub(crate) font_descriptor: FontDescriptor,
    pub(crate) text_background_enabled: bool,
    pub(crate) arrow_length: f64,
    pub(crate) arrow_angle: f64,
    pub(crate) arrow_head_at_end: bool,
    pub(crate) ui_visibility: crate::input::state::UiVisibility,
    pub(crate) boards_config: BoardsConfig,
    pub(crate) action_map: HashMap<Shortcut, Action>,
    pub(crate) max_shapes_per_frame: usize,
    pub(crate) click_highlight_settings: ClickHighlightSettings,
    pub(crate) undo_all_delay_ms: u64,
    pub(crate) redo_all_delay_ms: u64,
    pub(crate) custom_section_enabled: bool,
    pub(crate) custom_undo_delay_ms: u64,
    pub(crate) custom_redo_delay_ms: u64,
    pub(crate) custom_undo_steps: usize,
    pub(crate) custom_redo_steps: usize,
    pub(crate) presenter_mode_config: crate::config::PresenterModeConfig,
}

impl InputState {
    /// Creates input state from an explicit runtime seed.
    ///
    /// Screen dimensions default to zero and the backend updates them after
    /// surface configuration.
    pub(crate) fn from_seed(seed: InputStateSeed) -> Self {
        let InputStateSeed {
            color,
            thickness,
            eraser_size,
            eraser_mode,
            marker_opacity,
            fill_enabled,
            font_size,
            font_descriptor,
            text_background_enabled,
            arrow_length,
            arrow_angle,
            arrow_head_at_end,
            ui_visibility,
            boards_config,
            action_map,
            max_shapes_per_frame,
            click_highlight_settings,
            undo_all_delay_ms,
            redo_all_delay_ms,
            custom_section_enabled,
            custom_undo_delay_ms,
            custom_redo_delay_ms,
            custom_undo_steps,
            custom_redo_steps,
            presenter_mode_config,
        } = seed;
        let clamped_eraser = eraser_size.clamp(MIN_STROKE_THICKNESS, MAX_STROKE_THICKNESS);
        let mut tool_settings = PerToolDrawingSettings::new(color, thickness);
        tool_settings.step_marker.thickness =
            super::super::super::utility::default_step_marker_size(font_size);
        let sequence_trie =
            crate::input::state::core::utility::SequenceTrie::from_action_map(&action_map);
        let mut state = Self {
            input_effects: Default::default(),
            keymap_revision: 0,
            boards: BoardManager::from_config(boards_config),
            current_color: color,
            quick_colors: QuickColorPalette::default(),
            recent_colors: Vec::new(),
            current_thickness: thickness,
            tool_settings,
            pressure_variation_threshold: 0.1,
            pressure_thickness_edit_mode: PressureThicknessEditMode::Disabled,
            pressure_thickness_entry_mode: PressureThicknessEntryMode::PressureOnly,
            pressure_thickness_scale_step: 0.1,
            eraser_size: clamped_eraser,
            eraser_kind: EraserKind::Circle,
            eraser_mode,
            marker_opacity,
            pen_smoothing: crate::draw::shape::clamp_pen_smoothing(
                crate::config::DEFAULT_PEN_SMOOTHING,
            ),
            blur_style: BlurStyle::default(),
            spotlight_dim_opacity: 0.6,
            spotlight_feather: 0.35,
            spotlight_magnification: crate::draw::DEFAULT_SPOTLIGHT_MAGNIFICATION,
            current_font_size: font_size,
            font_descriptor,
            font_cycle: Vec::new(),
            font_picker: Default::default(),
            text_background_enabled,
            text_wrap_width: None,
            text_input_mode: TextInputMode::Plain,
            arrow_length,
            arrow_angle,
            arrow_head_at_end,
            arrow_style: ArrowStyle::default(),
            arrow_label_enabled: false,
            arrow_label_counter: 1,
            step_marker_counter: 1,
            modifiers: Modifiers::new(),
            drag_tool_bindings: DragToolBindings::default(),
            active_drag_button: None,
            active_drag_color: None,
            state: DrawingState::Idle,
            should_exit: false,
            explicit_exit_requested: false,
            needs_redraw: true,
            session_dirty: false,
            session_preflight_options: None,
            pending_save_as_overwrite: None,
            help_overlay: Default::default(),
            board_picker: Default::default(),
            command_palette: Default::default(),
            keybinding_capture_action: None,
            command_palette_toast_duration_ms: 1500,
            ui_visibility,
            zoom_chip_display: crate::config::ZoomChipDisplay::Always,
            presenter_mode: false,
            presenter_mode_config,
            render_profiles: crate::render_profiles::RenderProfileSet::default(),
            presenter_restore: None,
            focus_mode_restore: None,
            status_hud_hover: None,
            zoom_chip_hover: None,
            light_mode: false,
            light_mode_drawing: false,
            light_mode_restore: None,
            toolbar_visible: true,
            toolbar_top_visible: true,
            fill_enabled,
            polygon_sides: REGULAR_POLYGON_DEFAULT_SIDES,
            toolbar_top_pinned: true,
            toolbar_use_icons: true, // Default to icon mode
            toolbar_scale: 1.0,
            toolbar_layout_mode: crate::config::ToolbarLayoutMode::Regular,
            toolbar_mode_overrides: crate::config::ToolbarModeOverrides::default(),
            toolbar_items: crate::config::ToolbarItemsConfig::default(),
            resolved_toolbar_items: crate::config::ToolbarItemsConfig::default().resolved(),
            toolbar_customize_drag: None,
            toolbar_top_menu: crate::input::state::TopMenuState::Closed,
            toolbar_top_popover_scroll: 0.0,
            toolbar_top_minimized: false,
            toolbar_top_display_mode: crate::config::TopDisplayMode::Full,
            last_draw_activity: std::time::Instant::now(),
            precision_entry: None,
            toolbar_rebind_modifier: crate::config::ToolbarRebindModifier::default(),
            toolbar_customize_items_open: false,
            toolbar_customize_items_group: None,
            toolbar_status_bar_contents_open: false,
            screen_width: 0,
            screen_height: 0,
            active_output_label: None,
            board_previous_color: None,
            board_recent: Vec::new(),
            pending_board_delete: None,
            pending_page_delete: None,
            deleted_pages: Vec::new(),
            dirty_tracker: DirtyTracker::new(),
            last_provisional_bounds: None,
            last_text_preview_bounds: None,
            text_input_cursor_rect_dirty: false,
            text_input_external_change_dirty: false,
            text_input_generation: 0,
            text_input_revision: 0,
            action_map,
            action_bindings: HashMap::new(),
            sequence_trie,
            pending_sequence: None,
            consumed_pointer_buttons: HashSet::new(),
            spotlight_magnification_gesture: None,
            spotlight_wheel_value120_remainder: None,
            pending_onboarding_usage: PendingOnboardingUsage::default(),
            max_shapes_per_frame,
            click_highlight: ClickHighlightState::new(click_highlight_settings),
            input_hud: InputHudState::new(InputHudSettings::default()),
            tool_override: None,
            selection_state: SelectionState::None,
            last_selection_axis: None,
            context_menu: Default::default(),

            color_picker_popup: Default::default(),
            radial_menu: Default::default(),
            hit_test_cache: HashMap::new(),
            canvas_content_generation: 0,
            hit_test_tolerance: 6.0,
            max_linear_hit_test: 400,
            undo_stack_limit: 100,
            undo_all_delay_ms,
            redo_all_delay_ms,
            custom_undo_delay_ms,
            custom_redo_delay_ms,
            custom_undo_steps,
            custom_redo_steps,
            custom_section_enabled,
            ocr_scan: None,
            ui_toast: None,
            toast_queue: super::super::toast_queue::ToastQueue::default(),
            ui_toast_bounds: None,
            ui_toast_action_bounds: [None, None],
            selection_clipboard: None,
            selection_clipboard_generation: 0,
            selection_publish_state: super::super::types::SelectionPublishState::NotAttempted,
            clipboard_app_instance_id: new_clipboard_app_instance_id(),
            clipboard_paste_request_counter: 0,
            active_clipboard_paste_request_id: None,
            last_capture_path: None,
            last_text_click: None,
            last_polygon_click: None,
            text_edit_target: None,
            text_block_drag: None,
            text_edit_entry_feedback: None,
            ime: crate::input::state::ImeCompositionState::default(),
            pending_history: None,
            status_hud_layout: None,
            status_hud_rebuild_inputs: None,
            status_hud_press_pending: false,
            zoom_chip_layout: None,
            zoom_chip_press_pending: crate::ui::ZoomChipPress::None,
            spatial_index: None,
            last_pointer_position: (0, 0),
            last_canvas_pointer_position: (0, 0),
            pointer_seen: false,
            pending_menu_hover_recalc: false,
            shape_properties_panel: None,
            properties_panel_layout: None,
            pending_properties_hover_recalc: false,
            properties_panel_needs_refresh: false,
            frozen_active: false,
            eyedropper_ui_state: crate::input::state::core::EyedropperUiState::Inactive,
            region_select_ui_state: crate::input::state::core::RegionSelectUiState::Inactive,
            zoom_active: false,
            zoom_locked: false,
            zoom_scale: 1.0,
            zoom_view_offset: (0.0, 0.0),
            preset_slot_count: PRESET_SLOTS_MAX,
            presets: vec![None; PRESET_SLOTS_MAX],
            active_preset_slot: None,
            preset_feedback: vec![None; PRESET_SLOTS_MAX],
            tour_active: false,
            tour_step: 0,
            compositor_capabilities: CompositorCapabilities::default(),
            capability_toast_caps: None,
            blocked_action_feedback: None,
            pending_clipboard_fallback: None,
            deleted_boards: Vec::new(),
            status_change_highlight: None,
        };

        if state.click_highlight.uses_pen_color() {
            state.sync_highlight_color();
        }

        state
    }
}

fn new_clipboard_app_instance_id() -> String {
    let millis = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|duration| duration.as_millis())
        .unwrap_or(0);
    format!("{}-{}", std::process::id(), millis)
}
