use super::*;

pub fn toolbar_item_definitions() -> &'static [ToolbarItemDefinition] {
    TOOLBAR_ITEM_DEFINITIONS
}

const TOOLBAR_ITEM_DEFINITIONS: &[ToolbarItemDefinition] = &[
    item(ids::TOP_CHROME_DRAG, "Move top toolbar", Top, Chrome, None),
    item(ids::TOP_CHROME_LAYOUT, "Layout preset", Top, Chrome, None),
    item(ids::TOP_CHROME_ABOUT, "About Wayscriber", Top, Chrome, None),
    item(ids::TOP_CHROME_PIN, "Pin top toolbar", Top, Chrome, None),
    item(
        ids::TOP_CHROME_CLOSE,
        "Minimize top toolbar",
        Top,
        Chrome,
        None,
    ),
    item(ids::TOP_TOOL_SELECT, "Select", Top, Tool, None),
    item(ids::TOP_TOOL_PEN, "Pen", Top, Tool, None),
    item(ids::TOP_TOOL_MARKER, "Marker", Top, Tool, None),
    item(ids::TOP_TOOL_STEP_MARKER, "Step marker", Top, Tool, None),
    item(ids::TOP_TOOL_ERASER, "Eraser", Top, Tool, None),
    item(ids::TOP_TOOL_LINE, "Line", Top, Tool, None),
    item(ids::TOP_TOOL_RECT, "Rectangle", Top, Tool, None),
    item(ids::TOP_TOOL_ELLIPSE, "Ellipse", Top, Tool, None),
    item(ids::TOP_TOOL_ARROW, "Arrow", Top, Tool, None),
    item(ids::TOP_TOOL_BLUR, "Blur", Top, Tool, None),
    item(ids::TOP_TOOL_SPOTLIGHT, "Spotlight", Top, Tool, None),
    item(ids::TOP_TOOL_TRIANGLE, "Triangle", Top, Tool, None),
    item(
        ids::TOP_TOOL_PARALLELOGRAM,
        "Parallelogram",
        Top,
        Tool,
        None,
    ),
    item(ids::TOP_TOOL_RHOMBUS, "Rhombus", Top, Tool, None),
    item(
        ids::TOP_TOOL_REGULAR_POLYGON,
        "Regular polygon",
        Top,
        Tool,
        None,
    ),
    item(
        ids::TOP_TOOL_FREEFORM_POLYGON,
        "Freeform polygon",
        Top,
        Tool,
        None,
    ),
    item(
        ids::TOP_UTILITY_SHAPE_PICKER,
        "Shape picker",
        Top,
        Utility,
        None,
    ),
    item(ids::TOP_UTILITY_FILL, "Fill", Top, Utility, None),
    item(ids::TOP_UTILITY_TEXT, "Text", Top, Utility, None),
    item(
        ids::TOP_UTILITY_STICKY_NOTE,
        "Sticky note",
        Top,
        Utility,
        None,
    ),
    item(
        ids::TOP_UTILITY_CLEAR_CANVAS,
        "Clear canvas",
        Top,
        Utility,
        None,
    ),
    item(
        ids::TOP_UTILITY_SCREENSHOT,
        "Screenshot",
        Top,
        Utility,
        None,
    ),
    item(ids::TOP_UTILITY_OCR, "Copy text", Top, Utility, None),
    item(ids::TOP_UTILITY_HIGHLIGHT, "Highlight", Top, Utility, None),
    item(
        ids::TOP_UTILITY_HIGHLIGHT_RING,
        "Highlight ring",
        Top,
        Utility,
        None,
    ),
    item(
        ids::TOP_GROUP_QUICK_COLORS,
        "Quick colors",
        Top,
        Group,
        None,
    ),
    item(ids::TOP_UTILITY_UNDO, "Undo", Top, Utility, None),
    item(ids::TOP_UTILITY_REDO, "Redo", Top, Utility, None),
    item(ids::TOP_CHROME_OVERFLOW, "Overflow menu", Top, Chrome, None),
    item(
        ids::TOP_UTILITY_ICON_MODE_ICONS,
        "Use icons",
        Top,
        Utility,
        None,
    ),
    item(
        ids::TOP_UTILITY_ICON_MODE_TEXT,
        "Use text labels",
        Top,
        Utility,
        None,
    ),
    item(
        ids::SIDE_GROUP_STEP_UNDO,
        "Step Undo/Redo",
        Popover,
        Group,
        Some(ToolbarGroupId::StepUndo),
    ),
    item(
        ids::SIDE_GROUP_ACTIONS,
        "Actions",
        Popover,
        Group,
        Some(ToolbarGroupId::Actions),
    ),
    item(
        ids::SIDE_GROUP_PAGES,
        "Pages",
        Popover,
        Group,
        Some(ToolbarGroupId::Pages),
    ),
    item(
        ids::SIDE_GROUP_BOARDS,
        "Boards",
        Popover,
        Group,
        Some(ToolbarGroupId::Boards),
    ),
    item(
        ids::SIDE_GROUP_PRESETS,
        "Presets",
        Popover,
        Group,
        Some(ToolbarGroupId::Presets),
    ),
    item(
        ids::SIDE_GROUP_ACTIONS_ADVANCED,
        "Advanced actions",
        Popover,
        Group,
        None,
    ),
    item(
        ids::SIDE_GROUP_ZOOM_ACTIONS,
        "Zoom actions",
        Popover,
        Group,
        None,
    ),
    item(
        ids::SIDE_GROUP_TEXT_CONTROLS,
        "Text controls (persistent)",
        Popover,
        Group,
        None,
    ),
    item(
        ids::SIDE_ACTIONS_ZOOM_IN,
        "Zoom in",
        Popover,
        Action,
        Some(ToolbarGroupId::Actions),
    ),
    item(
        ids::SIDE_ACTIONS_ZOOM_OUT,
        "Zoom out",
        Popover,
        Action,
        Some(ToolbarGroupId::Actions),
    ),
    item(
        ids::SIDE_ACTIONS_RESET_ZOOM,
        "Reset zoom",
        Popover,
        Action,
        Some(ToolbarGroupId::Actions),
    ),
    item(
        ids::SIDE_ACTIONS_TOGGLE_ZOOM_LOCK,
        "Toggle zoom lock",
        Popover,
        Action,
        Some(ToolbarGroupId::Actions),
    ),
    item(
        ids::SIDE_ACTIONS_UNDO_ALL,
        "Undo all",
        Popover,
        Action,
        Some(ToolbarGroupId::Actions),
    ),
    item(
        ids::SIDE_ACTIONS_REDO_ALL,
        "Redo all",
        Popover,
        Action,
        Some(ToolbarGroupId::Actions),
    ),
    item(
        ids::SIDE_ACTIONS_UNDO_ALL_DELAYED,
        "Delayed undo all",
        Popover,
        Action,
        Some(ToolbarGroupId::Actions),
    ),
    item(
        ids::SIDE_ACTIONS_REDO_ALL_DELAYED,
        "Delayed redo all",
        Popover,
        Action,
        Some(ToolbarGroupId::Actions),
    ),
    item(
        ids::SIDE_ACTIONS_FREEZE,
        "Freeze",
        Popover,
        Action,
        Some(ToolbarGroupId::Actions),
    ),
    item(
        ids::SIDE_PAGES_PREVIOUS,
        "Previous page",
        Popover,
        Page,
        Some(ToolbarGroupId::Pages),
    ),
    item(
        ids::SIDE_PAGES_NEXT,
        "Next page",
        Popover,
        Page,
        Some(ToolbarGroupId::Pages),
    ),
    item(
        ids::SIDE_PAGES_NEW,
        "New page",
        Popover,
        Page,
        Some(ToolbarGroupId::Pages),
    ),
    item(
        ids::SIDE_PAGES_DUPLICATE,
        "Duplicate page",
        Popover,
        Page,
        Some(ToolbarGroupId::Pages),
    ),
    item(
        ids::SIDE_PAGES_DELETE,
        "Delete page",
        Popover,
        Page,
        Some(ToolbarGroupId::Pages),
    ),
    item(
        ids::SIDE_BOARDS_PICKER,
        "Board picker",
        Popover,
        Board,
        Some(ToolbarGroupId::Boards),
    ),
    item(
        ids::SIDE_BOARDS_PREVIOUS,
        "Previous board",
        Popover,
        Board,
        Some(ToolbarGroupId::Boards),
    ),
    item(
        ids::SIDE_BOARDS_NEXT,
        "Next board",
        Popover,
        Board,
        Some(ToolbarGroupId::Boards),
    ),
    item(
        ids::SIDE_BOARDS_NEW,
        "New board",
        Popover,
        Board,
        Some(ToolbarGroupId::Boards),
    ),
    item(
        ids::SIDE_BOARDS_DUPLICATE,
        "Duplicate board",
        Popover,
        Board,
        Some(ToolbarGroupId::Boards),
    ),
    item(
        ids::SIDE_BOARDS_DELETE,
        "Delete board",
        Popover,
        Board,
        Some(ToolbarGroupId::Boards),
    ),
    item(
        ids::SIDE_SETTINGS_CONTEXT_AWARE_UI,
        "Adapt to tool",
        Popover,
        Setting,
        Some(ToolbarGroupId::Settings),
    ),
    item(
        ids::SIDE_SETTINGS_TEXT_CONTROLS,
        "Text controls",
        Popover,
        Setting,
        Some(ToolbarGroupId::Settings),
    ),
    item(
        ids::SIDE_SETTINGS_STATUS_BAR,
        "Status bar",
        Popover,
        Setting,
        Some(ToolbarGroupId::Settings),
    ),
    item(
        ids::SIDE_SETTINGS_STATUS_BOARD_BADGE,
        "Status board badge",
        Popover,
        Setting,
        Some(ToolbarGroupId::Settings),
    ),
    item(
        ids::SIDE_SETTINGS_STATUS_PAGE_BADGE,
        "Status page badge",
        Popover,
        Setting,
        Some(ToolbarGroupId::Settings),
    ),
    item(
        ids::SIDE_SETTINGS_FLOATING_BADGE_ALWAYS,
        "Floating board/page badge",
        Popover,
        Setting,
        Some(ToolbarGroupId::Settings),
    ),
    item(
        ids::SIDE_SETTINGS_PRESET_TOASTS,
        "Preset toasts",
        Popover,
        Setting,
        Some(ToolbarGroupId::Settings),
    ),
    item(
        ids::SIDE_SETTINGS_PRESETS,
        "Presets toggle",
        Popover,
        Setting,
        Some(ToolbarGroupId::Settings),
    ),
    item(
        ids::SIDE_SETTINGS_ACTIONS,
        "Actions toggle",
        Popover,
        Setting,
        Some(ToolbarGroupId::Settings),
    ),
    item(
        ids::SIDE_SETTINGS_ZOOM_ACTIONS,
        "Zoom actions toggle",
        Popover,
        Setting,
        Some(ToolbarGroupId::Settings),
    ),
    item(
        ids::SIDE_SETTINGS_ADVANCED_ACTIONS,
        "Advanced actions toggle",
        Popover,
        Setting,
        Some(ToolbarGroupId::Settings),
    ),
    item(
        ids::SIDE_SETTINGS_BOARDS,
        "Boards toggle",
        Popover,
        Setting,
        Some(ToolbarGroupId::Settings),
    ),
    item(
        ids::SIDE_SETTINGS_PAGES,
        "Pages toggle",
        Popover,
        Setting,
        Some(ToolbarGroupId::Settings),
    ),
    item(
        ids::SIDE_SETTINGS_STEP_CONTROLS,
        "Multi-step undo/redo toggle",
        Popover,
        Setting,
        Some(ToolbarGroupId::Settings),
    ),
    item(
        ids::SIDE_SETTINGS_COMMAND_PALETTE,
        "Open command palette",
        Popover,
        Setting,
        Some(ToolbarGroupId::Settings),
    ),
    item(
        ids::SIDE_SETTINGS_CONFIGURATOR,
        "Open configurator",
        Popover,
        Setting,
        Some(ToolbarGroupId::Settings),
    ),
    item(
        ids::SIDE_SETTINGS_CONFIG_FILE,
        "Open config file",
        Popover,
        Setting,
        Some(ToolbarGroupId::Settings),
    ),
    item(
        ids::SIDE_SETTINGS_ABOUT,
        "Open About window",
        Popover,
        Setting,
        Some(ToolbarGroupId::Settings),
    ),
    item(
        ids::SIDE_SESSION_OPEN,
        "Open session",
        Popover,
        Session,
        Some(ToolbarGroupId::Session),
    ),
    item(
        ids::SIDE_SESSION_SAVE_AS,
        "Save session as",
        Popover,
        Session,
        Some(ToolbarGroupId::Session),
    ),
    item(
        ids::SIDE_SESSION_INFO,
        "Session info",
        Popover,
        Session,
        Some(ToolbarGroupId::Session),
    ),
    item(
        ids::SIDE_SESSION_CLEAR,
        "Clear session",
        Popover,
        Session,
        Some(ToolbarGroupId::Session),
    ),
    item(
        ids::SIDE_SESSION_MANAGER,
        "Session manager",
        Popover,
        Session,
        Some(ToolbarGroupId::Session),
    ),
];

const fn item(
    id: ToolbarItemId,
    label: &'static str,
    surface: ToolbarItemSurface,
    category: ToolbarItemCategory,
    group: Option<ToolbarGroupId>,
) -> ToolbarItemDefinition {
    ToolbarItemDefinition::new(id, label, surface, category, group)
}

use ToolbarItemCategory::{Action, Board, Chrome, Group, Page, Session, Setting, Tool, Utility};
use ToolbarItemSurface::{Popover, Top};
