use super::*;

pub fn toolbar_item_definitions() -> &'static [ToolbarItemDefinition] {
    TOOLBAR_ITEM_DEFINITIONS
}

const TOOLBAR_ITEM_DEFINITIONS: &[ToolbarItemDefinition] = &[
    item(ids::TOP_CHROME_DRAG, "Move top toolbar", Top, Chrome, None),
    item(ids::TOP_CHROME_PIN, "Pin top toolbar", Top, Chrome, None),
    item(
        ids::TOP_CHROME_CLOSE,
        "Minimize top toolbar",
        Top,
        Chrome,
        None,
    ),
    item(ids::TOP_TOOL_SELECT, "Select", Top, Tool, None),
    item(ids::TOP_TOOL_PEN, "Pen", Top, Tool, None),
    item(ids::TOP_TOOL_MARKER, "Marker", Top, Tool, None),
    item(ids::TOP_TOOL_STEP_MARKER, "Step marker", Top, Tool, None),
    item(ids::TOP_TOOL_ERASER, "Eraser", Top, Tool, None),
    item(ids::TOP_TOOL_LINE, "Line", Top, Tool, None),
    item(ids::TOP_TOOL_RECT, "Rectangle", Top, Tool, None),
    item(ids::TOP_TOOL_ELLIPSE, "Ellipse", Top, Tool, None),
    item(ids::TOP_TOOL_ARROW, "Arrow", Top, Tool, None),
    item(ids::TOP_TOOL_BLUR, "Blur", Top, Tool, None),
    item(ids::TOP_TOOL_TRIANGLE, "Triangle", Top, Tool, None),
    item(
        ids::TOP_TOOL_PARALLELOGRAM,
        "Parallelogram",
        Top,
        Tool,
        None,
    ),
    item(ids::TOP_TOOL_RHOMBUS, "Rhombus", Top, Tool, None),
    item(
        ids::TOP_TOOL_REGULAR_POLYGON,
        "Regular polygon",
        Top,
        Tool,
        None,
    ),
    item(
        ids::TOP_TOOL_FREEFORM_POLYGON,
        "Freeform polygon",
        Top,
        Tool,
        None,
    ),
    item(
        ids::TOP_UTILITY_SHAPE_PICKER,
        "Shape picker",
        Top,
        Utility,
        None,
    ),
    item(ids::TOP_UTILITY_FILL, "Fill", Top, Utility, None),
    item(ids::TOP_UTILITY_TEXT, "Text", Top, Utility, None),
    item(
        ids::TOP_UTILITY_STICKY_NOTE,
        "Sticky note",
        Top,
        Utility,
        None,
    ),
    item(
        ids::TOP_UTILITY_CLEAR_CANVAS,
        "Clear canvas",
        Top,
        Utility,
        None,
    ),
    item(
        ids::TOP_UTILITY_SCREENSHOT,
        "Screenshot",
        Top,
        Utility,
        None,
    ),
    item(ids::TOP_UTILITY_HIGHLIGHT, "Highlight", Top, Utility, None),
    item(
        ids::TOP_UTILITY_HIGHLIGHT_RING,
        "Highlight ring",
        Top,
        Utility,
        None,
    ),
    item(
        ids::TOP_GROUP_QUICK_COLORS,
        "Quick colors",
        Top,
        Group,
        None,
    ),
    item(ids::TOP_UTILITY_UNDO, "Undo", Top, Utility, None),
    item(ids::TOP_UTILITY_REDO, "Redo", Top, Utility, None),
    item(ids::TOP_CHROME_OVERFLOW, "Overflow menu", Top, Chrome, None),
    item(
        ids::TOP_UTILITY_ICON_MODE_ICONS,
        "Use icons",
        Top,
        Utility,
        None,
    ),
    item(
        ids::TOP_UTILITY_ICON_MODE_TEXT,
        "Use text labels",
        Top,
        Utility,
        None,
    ),
    item(
        ids::SIDE_GROUP_COLORS,
        "Colors",
        Side,
        Group,
        Some(ToolbarGroupId::Colors),
    ),
    item(
        ids::SIDE_GROUP_THICKNESS,
        "Thickness",
        Side,
        Group,
        Some(ToolbarGroupId::Thickness),
    ),
    item(
        ids::SIDE_GROUP_ERASER_MODE,
        "Eraser mode",
        Side,
        Group,
        Some(ToolbarGroupId::EraserMode),
    ),
    item(
        ids::SIDE_GROUP_POLYGON_SIDES,
        "Polygon sides",
        Side,
        Group,
        Some(ToolbarGroupId::PolygonSides),
    ),
    item(
        ids::SIDE_GROUP_ARROW_LABELS,
        "Arrow labels",
        Side,
        Group,
        Some(ToolbarGroupId::ArrowLabels),
    ),
    item(
        ids::SIDE_GROUP_STEP_MARKERS,
        "Step markers",
        Side,
        Group,
        Some(ToolbarGroupId::StepMarkers),
    ),
    item(
        ids::SIDE_GROUP_STEP_UNDO,
        "Step Undo/Redo",
        Side,
        Group,
        Some(ToolbarGroupId::StepUndo),
    ),
    item(
        ids::SIDE_GROUP_MARKER_OPACITY,
        "Marker opacity",
        Side,
        Group,
        Some(ToolbarGroupId::MarkerOpacity),
    ),
    item(
        ids::SIDE_GROUP_TEXT_SIZE,
        "Text size",
        Side,
        Group,
        Some(ToolbarGroupId::TextSize),
    ),
    item(
        ids::SIDE_GROUP_FONT,
        "Font",
        Side,
        Group,
        Some(ToolbarGroupId::Font),
    ),
    item(
        ids::SIDE_GROUP_ACTIONS,
        "Actions",
        Side,
        Group,
        Some(ToolbarGroupId::Actions),
    ),
    item(
        ids::SIDE_GROUP_PAGES,
        "Pages",
        Side,
        Group,
        Some(ToolbarGroupId::Pages),
    ),
    item(
        ids::SIDE_GROUP_BOARDS,
        "Boards",
        Side,
        Group,
        Some(ToolbarGroupId::Boards),
    ),
    item(
        ids::SIDE_GROUP_PRESETS,
        "Presets",
        Side,
        Group,
        Some(ToolbarGroupId::Presets),
    ),
    item(
        ids::SIDE_GROUP_SETTINGS,
        "Settings",
        Side,
        Group,
        Some(ToolbarGroupId::Settings),
    ),
    item(
        ids::SIDE_GROUP_ACTIONS_ADVANCED,
        "Advanced actions",
        Side,
        Group,
        None,
    ),
    item(
        ids::SIDE_GROUP_ZOOM_ACTIONS,
        "Zoom actions",
        Side,
        Group,
        None,
    ),
    item(
        ids::SIDE_GROUP_TEXT_CONTROLS,
        "Text controls (persistent)",
        Side,
        Group,
        None,
    ),
    item(
        ids::SIDE_GROUP_SESSION,
        "Session",
        Side,
        Group,
        Some(ToolbarGroupId::Session),
    ),
    item(
        ids::SIDE_ACTIONS_UNDO,
        "Undo",
        Side,
        Action,
        Some(ToolbarGroupId::Actions),
    ),
    item(
        ids::SIDE_ACTIONS_REDO,
        "Redo",
        Side,
        Action,
        Some(ToolbarGroupId::Actions),
    ),
    item(
        ids::SIDE_ACTIONS_CLEAR_CANVAS,
        "Clear canvas",
        Side,
        Action,
        Some(ToolbarGroupId::Actions),
    ),
    item(
        ids::SIDE_ACTIONS_ZOOM_IN,
        "Zoom in",
        Side,
        Action,
        Some(ToolbarGroupId::Actions),
    ),
    item(
        ids::SIDE_ACTIONS_ZOOM_OUT,
        "Zoom out",
        Side,
        Action,
        Some(ToolbarGroupId::Actions),
    ),
    item(
        ids::SIDE_ACTIONS_RESET_ZOOM,
        "Reset zoom",
        Side,
        Action,
        Some(ToolbarGroupId::Actions),
    ),
    item(
        ids::SIDE_ACTIONS_TOGGLE_ZOOM_LOCK,
        "Toggle zoom lock",
        Side,
        Action,
        Some(ToolbarGroupId::Actions),
    ),
    item(
        ids::SIDE_ACTIONS_UNDO_ALL,
        "Undo all",
        Side,
        Action,
        Some(ToolbarGroupId::Actions),
    ),
    item(
        ids::SIDE_ACTIONS_REDO_ALL,
        "Redo all",
        Side,
        Action,
        Some(ToolbarGroupId::Actions),
    ),
    item(
        ids::SIDE_ACTIONS_UNDO_ALL_DELAYED,
        "Delayed undo all",
        Side,
        Action,
        Some(ToolbarGroupId::Actions),
    ),
    item(
        ids::SIDE_ACTIONS_REDO_ALL_DELAYED,
        "Delayed redo all",
        Side,
        Action,
        Some(ToolbarGroupId::Actions),
    ),
    item(
        ids::SIDE_ACTIONS_FREEZE,
        "Freeze",
        Side,
        Action,
        Some(ToolbarGroupId::Actions),
    ),
    item(
        ids::SIDE_PAGES_PREVIOUS,
        "Previous page",
        Side,
        Page,
        Some(ToolbarGroupId::Pages),
    ),
    item(
        ids::SIDE_PAGES_NEXT,
        "Next page",
        Side,
        Page,
        Some(ToolbarGroupId::Pages),
    ),
    item(
        ids::SIDE_PAGES_NEW,
        "New page",
        Side,
        Page,
        Some(ToolbarGroupId::Pages),
    ),
    item(
        ids::SIDE_PAGES_DUPLICATE,
        "Duplicate page",
        Side,
        Page,
        Some(ToolbarGroupId::Pages),
    ),
    item(
        ids::SIDE_PAGES_DELETE,
        "Delete page",
        Side,
        Page,
        Some(ToolbarGroupId::Pages),
    ),
    item(
        ids::SIDE_BOARDS_PICKER,
        "Board picker",
        Side,
        Board,
        Some(ToolbarGroupId::Boards),
    ),
    item(
        ids::SIDE_BOARDS_PREVIOUS,
        "Previous board",
        Side,
        Board,
        Some(ToolbarGroupId::Boards),
    ),
    item(
        ids::SIDE_BOARDS_NEXT,
        "Next board",
        Side,
        Board,
        Some(ToolbarGroupId::Boards),
    ),
    item(
        ids::SIDE_BOARDS_NEW,
        "New board",
        Side,
        Board,
        Some(ToolbarGroupId::Boards),
    ),
    item(
        ids::SIDE_BOARDS_DUPLICATE,
        "Duplicate board",
        Side,
        Board,
        Some(ToolbarGroupId::Boards),
    ),
    item(
        ids::SIDE_BOARDS_DELETE,
        "Delete board",
        Side,
        Board,
        Some(ToolbarGroupId::Boards),
    ),
    item(
        ids::SIDE_BOARDS_RENAME,
        "Rename board",
        Side,
        Board,
        Some(ToolbarGroupId::Boards),
    ),
    item(
        ids::SIDE_SETTINGS_CONTEXT_AWARE_UI,
        "Adapt to tool",
        Side,
        Setting,
        Some(ToolbarGroupId::Settings),
    ),
    item(
        ids::SIDE_SETTINGS_TEXT_CONTROLS,
        "Text controls",
        Side,
        Setting,
        Some(ToolbarGroupId::Settings),
    ),
    item(
        ids::SIDE_SETTINGS_STATUS_BAR,
        "Status bar",
        Side,
        Setting,
        Some(ToolbarGroupId::Settings),
    ),
    item(
        ids::SIDE_SETTINGS_STATUS_BOARD_BADGE,
        "Status board badge",
        Side,
        Setting,
        Some(ToolbarGroupId::Settings),
    ),
    item(
        ids::SIDE_SETTINGS_STATUS_PAGE_BADGE,
        "Status page badge",
        Side,
        Setting,
        Some(ToolbarGroupId::Settings),
    ),
    item(
        ids::SIDE_SETTINGS_FLOATING_BADGE_ALWAYS,
        "Floating board/page badge",
        Side,
        Setting,
        Some(ToolbarGroupId::Settings),
    ),
    item(
        ids::SIDE_SETTINGS_PRESET_TOASTS,
        "Preset toasts",
        Side,
        Setting,
        Some(ToolbarGroupId::Settings),
    ),
    item(
        ids::SIDE_SETTINGS_PRESETS,
        "Presets toggle",
        Side,
        Setting,
        Some(ToolbarGroupId::Settings),
    ),
    item(
        ids::SIDE_SETTINGS_ACTIONS,
        "Actions toggle",
        Side,
        Setting,
        Some(ToolbarGroupId::Settings),
    ),
    item(
        ids::SIDE_SETTINGS_ZOOM_ACTIONS,
        "Zoom actions toggle",
        Side,
        Setting,
        Some(ToolbarGroupId::Settings),
    ),
    item(
        ids::SIDE_SETTINGS_ADVANCED_ACTIONS,
        "Advanced actions toggle",
        Side,
        Setting,
        Some(ToolbarGroupId::Settings),
    ),
    item(
        ids::SIDE_SETTINGS_BOARDS,
        "Boards toggle",
        Side,
        Setting,
        Some(ToolbarGroupId::Settings),
    ),
    item(
        ids::SIDE_SETTINGS_PAGES,
        "Pages toggle",
        Side,
        Setting,
        Some(ToolbarGroupId::Settings),
    ),
    item(
        ids::SIDE_SETTINGS_STEP_CONTROLS,
        "Multi-step undo/redo toggle",
        Side,
        Setting,
        Some(ToolbarGroupId::Settings),
    ),
    item(
        ids::SIDE_SETTINGS_COMMAND_PALETTE,
        "Open command palette",
        Side,
        Setting,
        Some(ToolbarGroupId::Settings),
    ),
    item(
        ids::SIDE_SETTINGS_CONFIGURATOR,
        "Open configurator",
        Side,
        Setting,
        Some(ToolbarGroupId::Settings),
    ),
    item(
        ids::SIDE_SETTINGS_CONFIG_FILE,
        "Open config file",
        Side,
        Setting,
        Some(ToolbarGroupId::Settings),
    ),
    item(
        ids::SIDE_SESSION_OPEN,
        "Open session",
        Side,
        Session,
        Some(ToolbarGroupId::Session),
    ),
    item(
        ids::SIDE_SESSION_SAVE_AS,
        "Save session as",
        Side,
        Session,
        Some(ToolbarGroupId::Session),
    ),
    item(
        ids::SIDE_SESSION_INFO,
        "Session info",
        Side,
        Session,
        Some(ToolbarGroupId::Session),
    ),
    item(
        ids::SIDE_SESSION_CLEAR,
        "Clear session",
        Side,
        Session,
        Some(ToolbarGroupId::Session),
    ),
    item(
        ids::SIDE_SESSION_MANAGER,
        "Session manager",
        Side,
        Session,
        Some(ToolbarGroupId::Session),
    ),
    item(
        ids::SIDE_TOOL_OPTIONS_COLOR,
        "Color",
        Side,
        ToolOption,
        Some(ToolbarGroupId::Colors),
    ),
    item(
        ids::SIDE_TOOL_OPTIONS_THICKNESS,
        "Thickness",
        Side,
        ToolOption,
        Some(ToolbarGroupId::Thickness),
    ),
    item(
        ids::SIDE_TOOL_OPTIONS_MARKER_OPACITY,
        "Marker opacity",
        Side,
        ToolOption,
        Some(ToolbarGroupId::MarkerOpacity),
    ),
    item(
        ids::SIDE_TOOL_OPTIONS_ERASER_MODE,
        "Eraser mode",
        Side,
        ToolOption,
        Some(ToolbarGroupId::EraserMode),
    ),
    item(
        ids::SIDE_TOOL_OPTIONS_FONT_SIZE,
        "Font size",
        Side,
        ToolOption,
        Some(ToolbarGroupId::TextSize),
    ),
    item(
        ids::SIDE_TOOL_OPTIONS_FONT_FAMILY,
        "Font family",
        Side,
        ToolOption,
        Some(ToolbarGroupId::Font),
    ),
    item(
        ids::SIDE_TOOL_OPTIONS_POLYGON_SIDES,
        "Polygon sides",
        Side,
        ToolOption,
        Some(ToolbarGroupId::PolygonSides),
    ),
    item(
        ids::SIDE_TOOL_OPTIONS_ARROW_LABELS,
        "Arrow labels",
        Side,
        ToolOption,
        Some(ToolbarGroupId::ArrowLabels),
    ),
    item(
        ids::SIDE_TOOL_OPTIONS_STEP_MARKER_RESET,
        "Reset step marker",
        Side,
        ToolOption,
        Some(ToolbarGroupId::StepMarkers),
    ),
];

const fn item(
    id: ToolbarItemId,
    label: &'static str,
    surface: ToolbarItemSurface,
    category: ToolbarItemCategory,
    group: Option<ToolbarGroupId>,
) -> ToolbarItemDefinition {
    ToolbarItemDefinition::new(id, label, surface, category, group)
}

use ToolbarItemCategory::{
    Action, Board, Chrome, Group, Page, Session, Setting, Tool, ToolOption, Utility,
};
use ToolbarItemSurface::{Side, Top};
