use super::core::{ContextMenuKind, ContextMenuState, MenuCommand};
use super::*;
use crate::config::{Action, BoardsConfig, ColorSpec, ToolPresetConfig};
use crate::draw::{Color, EraserKind, FontDescriptor, Shape, frame::UndoAction};
use crate::input::{ClickHighlightSettings, EraserMode, Key, MouseButton, Tool};
use crate::util;

mod helpers;
use helpers::{create_test_input_state, create_test_input_state_with_keybindings};

mod action_bindings;
mod arrow_labels;
mod basics;
mod board_picker;
mod boards;
mod delete_restore;
mod drawing;
mod erase;
mod menus;
mod pages;
mod presenter_mode;
mod pressure_modes;
mod properties_panel;
mod radial_menu;
mod selection;
mod step_markers;
mod text_edit;
mod text_input;
mod tool_controls;
mod transform;
