use super::KeybindingField;
use wayscriber::config::{Action, KeybindingsConfig, action_label};

impl KeybindingField {
    pub fn action(self) -> Option<Action> {
        let key = self.field_key();
        KeybindingsConfig::configurable_actions()
            .iter()
            .copied()
            .find(|action| KeybindingsConfig::config_key_for_action(*action) == Some(key))
    }

    pub fn label(&self) -> &'static str {
        self.action()
            .map(action_label)
            .unwrap_or_else(|| self.field_key())
    }

    pub fn field_key(&self) -> &'static str {
        match self {
            Self::Exit => "exit",
            Self::EnterTextMode => "enter_text_mode",
            Self::EnterStickyNoteMode => "enter_sticky_note_mode",
            Self::ClearCanvas => "clear_canvas",
            Self::Undo => "undo",
            Self::Redo => "redo",
            Self::UndoAll => "undo_all",
            Self::RedoAll => "redo_all",
            Self::UndoAllDelayed => "undo_all_delayed",
            Self::RedoAllDelayed => "redo_all_delayed",
            Self::DuplicateSelection => "duplicate_selection",
            Self::CopySelection => "copy_selection",
            Self::PasteSelection => "paste_selection",
            Self::SelectAll => "select_all",
            Self::MoveSelectionToFront => "move_selection_to_front",
            Self::MoveSelectionToBack => "move_selection_to_back",
            Self::NudgeSelectionUp => "nudge_selection_up",
            Self::NudgeSelectionDown => "nudge_selection_down",
            Self::NudgeSelectionLeft => "nudge_selection_left",
            Self::NudgeSelectionRight => "nudge_selection_right",
            Self::NudgeSelectionUpLarge => "nudge_selection_up_large",
            Self::NudgeSelectionDownLarge => "nudge_selection_down_large",
            Self::MoveSelectionToStart => "move_selection_to_start",
            Self::MoveSelectionToEnd => "move_selection_to_end",
            Self::MoveSelectionToTop => "move_selection_to_top",
            Self::MoveSelectionToBottom => "move_selection_to_bottom",
            Self::DeleteSelection => "delete_selection",
            Self::IncreaseThickness => "increase_thickness",
            Self::DecreaseThickness => "decrease_thickness",
            Self::IncreaseMarkerOpacity => "increase_marker_opacity",
            Self::DecreaseMarkerOpacity => "decrease_marker_opacity",
            Self::SelectSelectionTool => "select_selection_tool",
            Self::SelectPenTool => "select_pen_tool",
            Self::SelectEraserTool => "select_eraser_tool",
            Self::ToggleEraserMode => "toggle_eraser_mode",
            Self::SelectMarkerTool => "select_marker_tool",
            Self::SelectStepMarkerTool => "select_step_marker_tool",
            Self::SelectLineTool => "select_line_tool",
            Self::SelectRectTool => "select_rect_tool",
            Self::SelectEllipseTool => "select_ellipse_tool",
            Self::SelectArrowTool => "select_arrow_tool",
            Self::SelectTriangleTool => "select_triangle_tool",
            Self::SelectParallelogramTool => "select_parallelogram_tool",
            Self::SelectRhombusTool => "select_rhombus_tool",
            Self::SelectRegularPolygonTool => "select_regular_polygon_tool",
            Self::SelectFreeformPolygonTool => "select_freeform_polygon_tool",
            Self::SelectBlurTool => "select_blur_tool",
            Self::SelectSpotlightTool => "select_spotlight_tool",
            Self::CycleBlurStyle => "cycle_blur_style",
            Self::CycleArrowStyle => "cycle_arrow_style",
            Self::SelectHighlightTool => "select_highlight_tool",
            Self::IncreaseFontSize => "increase_font_size",
            Self::DecreaseFontSize => "decrease_font_size",
            Self::ToggleWhiteboard => "toggle_whiteboard",
            Self::ToggleBlackboard => "toggle_blackboard",
            Self::ReturnToTransparent => "return_to_transparent",
            Self::PagePrev => "page_prev",
            Self::PageNext => "page_next",
            Self::PageNew => "page_new",
            Self::PageDuplicate => "page_duplicate",
            Self::PageDelete => "page_delete",
            Self::Board1 => "board_1",
            Self::Board2 => "board_2",
            Self::Board3 => "board_3",
            Self::Board4 => "board_4",
            Self::Board5 => "board_5",
            Self::Board6 => "board_6",
            Self::Board7 => "board_7",
            Self::Board8 => "board_8",
            Self::Board9 => "board_9",
            Self::FocusNextOutput => "focus_next_output",
            Self::FocusPrevOutput => "focus_prev_output",
            Self::ToggleLightMode => "toggle_light_mode",
            Self::ToggleLightModeDrawing => "toggle_light_mode_drawing",
            Self::ToggleRadialMenu => "toggle_radial_menu",
            Self::BoardNext => "board_next",
            Self::BoardPrev => "board_prev",
            Self::BoardNew => "board_new",
            Self::BoardDuplicate => "board_duplicate",
            Self::BoardDelete => "board_delete",
            Self::BoardPicker => "board_picker",
            Self::ToggleHelp => "toggle_help",
            Self::ToggleQuickHelp => "toggle_quick_help",
            Self::ToggleStatusBar => "toggle_status_bar",
            Self::ToggleFloatingBadge => "toggle_floating_badge",
            Self::ToggleZoomChip => "toggle_zoom_chip",
            Self::ToggleFocusMode => "toggle_focus_mode",
            Self::ToggleClickHighlight => "toggle_click_highlight",
            Self::ToggleInputHud => "toggle_input_hud",
            Self::ToggleToolbar => "toggle_toolbar",
            Self::CycleToolbarDisplay => "cycle_toolbar_display",
            Self::TogglePresenterMode => "toggle_presenter_mode",
            Self::RenderProfileNext => "render_profile_next",
            Self::RenderProfilePrevious => "render_profile_previous",
            Self::RenderProfileOff => "render_profile_off",
            Self::ToggleFill => "toggle_fill",
            Self::ToggleHighlightTool => "toggle_highlight_tool",
            Self::ToggleSelectionProperties => "toggle_selection_properties",
            Self::OpenContextMenu => "open_context_menu",
            Self::OpenConfigurator => "open_configurator",
            Self::OpenAbout => "open_about",
            Self::ToggleCommandPalette => "toggle_command_palette",
            Self::SetColorRed => "set_color_red",
            Self::SetColorGreen => "set_color_green",
            Self::SetColorBlue => "set_color_blue",
            Self::SetColorYellow => "set_color_yellow",
            Self::SetColorOrange => "set_color_orange",
            Self::SetColorPink => "set_color_pink",
            Self::SetColorWhite => "set_color_white",
            Self::SetColorBlack => "set_color_black",
            Self::PickScreenColor => "pick_screen_color",
            Self::CaptureFullScreen => "capture_full_screen",
            Self::CaptureActiveWindow => "capture_active_window",
            Self::CaptureSelection => "capture_selection",
            Self::CaptureClipboardFull => "capture_clipboard_full",
            Self::CaptureFileFull => "capture_file_full",
            Self::CaptureClipboardSelection => "capture_clipboard_selection",
            Self::CaptureFileSelection => "capture_file_selection",
            Self::CaptureClipboardRegion => "capture_clipboard_region",
            Self::CaptureFileRegion => "capture_file_region",
            Self::CaptureRegionInteractive => "capture_region_interactive",
            Self::MeasureMode => "measure_mode",
            Self::ExportCanvasFile => "export_canvas_file",
            Self::ExportCanvasClipboard => "export_canvas_clipboard",
            Self::ExportCanvasClipboardAndFile => "export_canvas_clipboard_and_file",
            Self::ExportBoardPdfFile => "export_board_pdf_file",
            Self::ExportAllBoardsPdfFile => "export_all_boards_pdf_file",
            Self::OpenCaptureFolder => "open_capture_folder",
            Self::CopyTextFromScreen => "copy_text_from_screen",
            Self::ToggleFrozenMode => "toggle_frozen_mode",
            Self::ZoomIn => "zoom_in",
            Self::ZoomOut => "zoom_out",
            Self::ResetZoom => "reset_zoom",
            Self::ToggleZoomLock => "toggle_zoom_lock",
            Self::RefreshZoomCapture => "refresh_zoom_capture",
            Self::ResetArrowLabels => "reset_arrow_labels",
            Self::ResetStepMarkers => "reset_step_markers",
            Self::ApplyPreset1 => "apply_preset_1",
            Self::ApplyPreset2 => "apply_preset_2",
            Self::ApplyPreset3 => "apply_preset_3",
            Self::ApplyPreset4 => "apply_preset_4",
            Self::ApplyPreset5 => "apply_preset_5",
            Self::SavePreset1 => "save_preset_1",
            Self::SavePreset2 => "save_preset_2",
            Self::SavePreset3 => "save_preset_3",
            Self::SavePreset4 => "save_preset_4",
            Self::SavePreset5 => "save_preset_5",
            Self::ClearPreset1 => "clear_preset_1",
            Self::ClearPreset2 => "clear_preset_2",
            Self::ClearPreset3 => "clear_preset_3",
            Self::ClearPreset4 => "clear_preset_4",
            Self::ClearPreset5 => "clear_preset_5",
        }
    }

    /// The field holding one `[keybindings]` key, if this build has it.
    ///
    /// The migration preview names its changes by the main crate's config key,
    /// which is where a draft edit has to land. A key with no field here is a
    /// binding the configurator cannot show, so it is skipped rather than
    /// written blind.
    pub fn from_field_key(key: &str) -> Option<Self> {
        Self::all()
            .into_iter()
            .find(|field| field.field_key() == key)
    }
}
