#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ToggleField {
    DrawingTextBackground,
    DrawingFillEnabled,
    PerformanceVsync,
    UiShowStatusBar,
    UiStatusBarInteractive,
    UiActiveOutputBadge,
    UiShowStatusSelectionInfo,
    UiShowStatusColor,
    UiShowStatusTool,
    UiShowStatusSize,
    UiShowStatusContextIndicators,
    UiShowStatusHelp,
    UiShowStatusAbout,
    UiShowFrozenBadge,
    UiShowCapabilitiesWarning,
    UiShowOnboardingHints,
    UiHelpOverlayContextFilter,
    UiContextMenuEnabled,
    UiXdgFullscreen,
    UiXdgKeepOnFocusLoss,
    UiToolbarTopPinned,
    UiToolbarUseIcons,
    UiToolbarShowMoreColors,
    UiToolbarPresetToasts,
    UiToolbarShowPresets,
    UiToolbarShowActionsSection,
    UiToolbarShowActionsAdvanced,
    UiToolbarShowZoomActions,
    UiToolbarShowPagesSection,
    UiToolbarShowBoardsSection,
    UiToolbarShowStepSection,
    UiToolbarShowTextControls,
    UiToolbarShowDelaySliders,
    UiToolbarShowMarkerOpacitySection,
    UiToolbarShowToolPreview,
    UiToolbarForceInline,
    UiClickHighlightEnabled,
    UiClickHighlightShowOnHighlightTool,
    UiClickHighlightUsePenColor,
    UiClickHighlightForceInLightMode,
    UiInputHudEnabled,
    UiInputHudShowMouse,
    UiInputHudShowBareModifiers,
    UiInputHudCombineRepeats,
    UiShowStatusBoardBadge,
    UiShowStatusPageBadge,
    UiShowToolbarHint,
    UiShowFloatingBadge,
    UiShowPageBadgeWithStatusBar,
    UiToolbarShowZoomChip,
    PresenterHideStatusBar,
    PresenterHideToolbars,
    PresenterHideToolPreview,
    PresenterCloseHelpOverlay,
    PresenterEnableClickHighlight,
    PresenterEnableInputHud,
    PresenterShowToast,
    BoardsAutoCreate,
    BoardsShowBadge,
    BoardsPersistCustomizations,
    CaptureEnabled,
    CaptureCopyToClipboard,
    CaptureExitAfter,
    ExportPdfLabelsEnabled,
    ExportPdfLabelBackgroundEnabled,
    SessionPersistTransparent,
    SessionPersistWhiteboard,
    SessionPersistBlackboard,
    SessionPersistHistory,
    SessionRestoreToolState,
    SessionPerOutput,
    SessionAutosaveEnabled,
    HistoryCustomSectionEnabled,
    ArrowHeadAtEnd,
    #[cfg(feature = "tablet-input")]
    TabletEnabled,
    #[cfg(feature = "tablet-input")]
    TabletPressureEnabled,
    #[cfg(feature = "tablet-input")]
    TabletAutoEraserSwitch,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
/// Copy for cheap capture in GTK signal-handler closures.
pub enum PresetToggleField {
    FillEnabled,
    TextBackgroundEnabled,
    ArrowHeadAtEnd,
    ShowStatusBar,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TextField {
    DrawingColorName,
    QuickColorLabel(usize),
    QuickColorName(usize),
    DrawingThickness,
    DrawingEraserSize,
    DrawingFontSize,
    DrawingPolygonSides,
    DrawingMarkerOpacity,
    DrawingFontFamily,
    DrawingFontWeight,
    DrawingFontStyle,
    DrawingHitTestTolerance,
    DrawingHitTestThreshold,
    DrawingUndoStackLimit,
    ArrowLength,
    ArrowAngle,
    PerformanceMaxFpsNoVsync,
    PerformanceUiAnimationFps,
    HistoryUndoAllDelayMs,
    HistoryRedoAllDelayMs,
    HistoryCustomUndoDelayMs,
    HistoryCustomRedoDelayMs,
    HistoryCustomUndoSteps,
    HistoryCustomRedoSteps,
    UiPreferredOutput,
    StatusFontSize,
    StatusPadding,
    StatusDotRadius,
    HighlightRadius,
    HighlightOutlineThickness,
    HighlightDurationMs,
    InputHudDisplayMs,
    InputHudFadeMs,
    InputHudMaxEntries,
    InputHudFontSize,
    HelpFontFamily,
    HelpFontSize,
    HelpLineHeight,
    HelpPadding,
    HelpBorderWidth,
    UiCommandPaletteToastDurationMs,
    CaptureSaveDirectory,
    CaptureFilename,
    CaptureFormat,
    CaptureOcrLanguages,
    ExportPdfFilenameTemplate,
    ExportPdfAllBoardsFilenameTemplate,
    ExportPdfCustomWidth,
    ExportPdfCustomHeight,
    ExportPdfContentSourcePadding,
    ExportPdfLabelTemplate,
    ExportPdfLabelFontFamily,
    ExportPdfLabelFontSize,
    ExportPdfLabelMargin,
    ExportPdfLabelPaddingX,
    ExportPdfLabelPaddingY,
    ToolbarTopOffset,
    ToolbarTopOffsetY,
    BoardsMaxCount,
    SessionCustomDirectory,
    SessionMaxShapesPerFrame,
    SessionMaxFileSizeMb,
    SessionAutoCompressThresholdKb,
    SessionMaxPersistedUndoDepth,
    SessionBackupRetention,
    SessionAutosaveIdleMs,
    SessionAutosaveIntervalMs,
    SessionAutosaveFailureBackoffMs,
    #[cfg(feature = "tablet-input")]
    TabletMinThickness,
    #[cfg(feature = "tablet-input")]
    TabletMaxThickness,
    #[cfg(feature = "tablet-input")]
    TabletPressureVariationThreshold,
    #[cfg(feature = "tablet-input")]
    TabletPressureScaleStep,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
/// Copy for cheap capture in GTK signal-handler closures.
pub enum PresetTextField {
    Name,
    ColorName,
    Size,
    MarkerOpacity,
    FontSize,
    ArrowLength,
    ArrowAngle,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum QuadField {
    StatusBarBg,
    StatusBarText,
    HelpBg,
    HelpBorder,
    HelpText,
    HighlightFill,
    HighlightOutline,
    ExportPdfLabelText,
    ExportPdfLabelBackground,
}
