#:include CoreTests.cs
#:include GtkGateParityTests.cs
#:include RepositoryContractTests.cs
#:include ReleaseParityRegressionTests.cs
#:include ReleaseRegressionTests.cs
#:include SignedRepositoryIntegrationTests.cs
#:include TestRepository.cs
#:include VersionMetadataFixture.cs
#:include VersionConsistencyTests.cs
#:include VersionReleaseCommandTests.cs
